@startuml

!theme mars

Person as "Admin ou auteur" -> TrickController : GET /tricks/{slug}/update
alt Is not author
    TrickController -[#red]> Twig : render('401')
    Twig -[#red]-> Person : Affichage de la page 401 : Unauthorized
else Is author
    TrickController -> Database : récupération de la figure
    Database --> TrickController : return
    TrickController -[#green]> Twig : render('tricks/create', ['trick' => $trick])
    Twig --[#green]> Person : affichage du formulaire pré-rempli
end


Person -> TrickController : PUT /tricks/{slug}/update
alt Is not author
TrickController -[#red]> Twig : render('401')
Twig -[#red]-> Person : Affichage de la page 401 : Unauthorized
else Is author
    TrickController -> Validator : validation des données
    Validator --> TrickController : return

    alt Is not valid
        TrickController -[#red]> Twig : render('tricks/create')
        Twig -[#red]-> Person : Affichage du formulaire avec un message d'erreur
    else Is valid
        TrickController -> Database : enregistrement de la figure
        Database --> TrickController : return

        alt Is not saved
            TrickController -[#red]> Twig : render('tricks/create')
            Twig -[#red]-> Person : Affichage du formulaire avec un message d'erreur
        else Is saved
            TrickController -[#green]> Twig : redirectToRoute('trick', ['slug' => $slug] )
            Twig -[#green]-> Person : Affichage de la figure avec un message de succès
        end
    end
end

@enduml