@startuml

!theme mars

header Cette fonctionnalité a été ajoutée pour améliorer la modération sur le site
title Débloquer un utilisateur

Person as "Admin" -> UserController : GET /users/{username}/unblock
alt Is not admin
    UserController -[#red]> Twig : render('401')
    Twig -[#red]-> Person : Affichage de la page 401 : Unauthorized
else Is admin
    UserController -> Database : déblocage de l'utilisateur
    Database --> UserController : return
end
@enduml