@startuml

!theme plain
left to right direction

:Admin:

package figures {
    Admin ---> (Consulter les figures)
    Admin ---> (Consulter une figure)
    Admin ---> (Créer une figure)
    Admin ---> (Modifier une de ses figures)
    Admin ---> (Supprimer une de ses figures)
    Admin ---> (Bloguer une figure)
    Admin ---> (Débloquer une figure)
}

package commentaires {
    (Consulter les commentaires) <--- Admin
    (Commenter une  figure) <--- Admin
    (Modifier un de ses commentaires) <--- Admin
    (Supprimer un de ses commentaires) <--- Admin
    (Bloquer un commentaire) <--- Admin
    (Débloquer un commentaire) <--- Admin
}

package utilisateur {
    (Supprimer un utilisateur) <--- Admin
    (Bloquer un utilisateur) <--- Admin
    (Débloquer un utilisateur) <--- Admin
}

package compte {
     Admin ---> (Se déconnecter)
}


@enduml