@startuml

!theme mars

header Cette fonctionnalité a été ajoutée pour améliorer la modération sur le site
title Débloquer un commentaire

Person as "Admin" -> CommentController : GET /comment/{id}/unblock

alt Is not admin
CommentController -[#red]> Twig : redirect('401')
Twig --[#red]> Person : affichage de la page 401 : Unauthorized
else Is admin
CommentController -> Database : débloquer le commentaire
Database --> CommentController : return
    alt Is not unblocked
    CommentController -[#red]> Twig : redirect('/admin/comments', ['error' => $error]})
    Twig --[#red]> Person : affichage d'un message d'erreur
    else Is unblocked
    CommentController -[#green]> Twig : render('/admin/comments', ['success' => $success]})
    Twig --[#green]> Person : affichage d'un message de succès
    end
end
@enduml